version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
    restart: unless-stopped
